### ISSUE TITLE
Add X-Tls-Protocol and X-Tls-Cipher support

### ISSUE THREAD

**Issue by pv3ntur1** [diennea/carapaceproxy#144]
Just like done with X-Forwarded-For, we need to add  X-Tls-Protocol and X-Tls-Cipher info from clients to backends.

**Comment by eolivelli** [comment]
How does this work with Tomcat ?
X-Forwarded-For is handled by a specific Valve and the original remote address is seen by the application transparently.
What is the meaning of such other headers ? is there any particular value ?

**Comment by aluccaroni** [comment]
X-Forwarded-For is standard, these two header are custom.
The main value is to report back to the application which protocol and cipher is been used by the client, mainly for debug and security audit purpose. This needs to be handled by the application behind carapace or, in a simpler way, simply printed out to the access log for further analysys. 

Since this information are used for debug I think a better way to handle this could be to save those information as statistics inside Carapace (log? jmx? db stats?).

**Comment by pv3nturi** [comment]
Carapace accesslog already prints that kind of info:
- <tls_protocol>: tls protocol used
-  <tls_cipher_suite>: cipher suite used
