### ISSUE TITLE
TLS - support OCSP stapling

### ISSUE THREAD

**Issue by aluccaroni** [diennea/carapaceproxy#158]
Support OCSP stapling for secure connections

**Comment by eolivelli** [comment]
This is already supported and enabled by default.
listerner.x.ocps=true|false

cc @hamadodene

**Comment by eolivelli** [comment]
we can create tests using Java client https://openjdk.java.net/jeps/249

**Comment by eolivelli** [comment]
A couple of thoughts:
- we can't create easily test cases, because OCSP requires a certificate issues by a CA with an OCSP responder
- I think that in the case from @hamadodene we are missing some configuration, in order to work the OSCP stapling protocol needs the certificate of the CA ( see OCSP Stapling config in Apache HTTPD and Nginx) https://www.digitalocean.com/community/tutorials/how-to-configure-ocsp-stapling-on-apache-and-nginx)

That said we should only take care of passing the correct configuration to BoringSSL (thru Netty): Enable OCSP Stapling + CA certificate as trusted certificate

In Carapace configuration you should use these configuration parameters to configure CA:
- listener.xxx.ssltruststorefile=
- listener.xxxx.ssltruststorepassword=

see more contents from:
- https://en.wikipedia.org/wiki/OCSP_stapling
- https://community.letsencrypt.org/t/howto-ocsp-stapling-for-nginx/13611/2

**Comment by eolivelli** [comment]
got it:
we need to perform OCSP manually, see
https://github.com/netty/netty/blob/4.1/example/src/main/java/io/netty/example/ocsp/OcspServerExample.java

but we have to implement some timer to perform the request after an expiration time, and we should think about sharing the OCSP response cluster wise
