### ISSUE TITLE
TLS - support TLS 1.3

### ISSUE THREAD

**Issue by hamadodene** [diennea/carapaceproxy#159]
Add  TLS 1.3  support

**Comment by eolivelli** [comment]
This should be already handled as we are using BoringSSL, maybe we only make it configurabile with #160

**Comment by aluccaroni** [comment]
@eolivelli we should support it since we use a newer release of netty-tcnative-boringssl-static than netty-tcnative-parent-2.0.18.Final (see https://github.com/netty/netty-tcnative/pull/406), but I'm unable to make it work in production (used multiple checker, always returning that TLS 1.3 is not offered)

**Comment by eolivelli** [comment]
This issue will be automatically fixed while doing #160 
https://stackoverflow.com/questions/53406502/how-to-enable-tlsv1-3-in-netty
